### ISSUE TITLE
Add to documentation staging mode

### ISSUE THREAD

**Issue by lc3t35** [cleverbeagle/seeder#12]
If you want to seed in staging mode, you add 
````
environments: ['development', 'staging'] 
````
but if you deploy using mup (or galaxy), you need to explicitly add in you mup.js config file (with ROOT_URL and such) 
````
NODE_ENV: 'staging',
````
Otherwise the condition won't match (default is production if not development)
````
environmentAllowed(environments) {
    if (environments) return environments.indexOf(process.env.NODE_ENV) > -1;
    return false;
}
````
Maybe a little warning in documentation might help.

**Comment by cleverbeagle** [comment]
Just made a little tweak to this in the docs [https://cleverbeagle.com/packages/seeder/usage#basic-usage](https://cleverbeagle.com/packages/seeder/usage#basic-usage) (under the `environment` field description).

**Comment by lc3t35** [comment]
Perfect !
