### ISSUE TITLE
Do not send emails for fake signups?

### ISSUE THREAD

**Issue by joncursi** [cleverbeagle/seeder#3]
Every time my meteor server restarts (often), a batch of 100 test users are created. Ever time a user is created, I send out two emails: one welcome email and a verification email. Sending these emails is taxing on local development, not necessary for development purposes, and costs $ (I use SES).

Is there a way we can specify to not fire emails on these fake sign ups?

**Comment by cleverbeagle** [comment]
@joncursi this would best be handled in your application logic. For things like this, I usually check to see if the environment is development and if it is, just log the data that _would_ be sent to the service to the server. Something like:

```javascript
const exampleData = {
  name: 'Jon Cursi',
  date: '2017-09-06',
};

if (Meteor.isDevelopment) { // alternatively process.env.NODE_ENV === 'development'
  console.log(exampleData);
} else {
  SES.send(exampleData);
}
```

**Comment by joncursi** [comment]
Good idea! Thank you
