### ISSUE TITLE
Method "data" to seed dependent is not called for seeder with collection other than Meteor.users

### ISSUE THREAD

**Issue by SergeJScr** [cleverbeagle/seeder#7]
Bug in index.js

    key: 'createData',
    value: function createData(collection, value) {
      //fixing bug - new var
      var data = value.data;
      ///
      var dataId = collection.insert(value);
      //fixing bug value.data lost
      //if (value.data) this.seedDependent(dataId, value.data);
      if (data) this.seedDependent(dataId, data);
    }
  }

**Comment by SergeJScr** [comment]
Double #4 Here is solution.

**Comment by cleverbeagle** [comment]
Fixed and available in 1.3.0 :)
